config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'welcome#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'dashboard' => 'dashboard#index'

  get 'tenants' => 'tenants#index'
  get 'tenants/show'

  resources :users

end

app/models/post.rb
class Post
  include PostsHelper
  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_id, type: Integer # in postgres
  field :tenant_id, type: BSON::ObjectId
  field :title, type: String
  field :body, type: String
  field :published, type: Boolean

  validates :title, :body, presence: true
  validates :title, length: { maximum: 255 }

  def self.search(pattern, title_body)
    regex = Regexp.new(".*#{pattern}.*")
    if pattern
      if title_body
        any_of({title: regex}, {body: regex})
      else
        # We probably want to limit what kind of patterns are allowed --- we
        # don't want a REGEX "injection attack" where a user puts in a tough
        # regex that searches for *everything* (e.g., a letter 'a').
        where(title: regex)
      end
    else
      where(nil)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]

  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if Rails.env.development? || logged_in?
      @posts = Post.search(params[:search], params[:title_body])
      # FIXME: only show own (authored) posts; for admins, show all posts
      if !admin_user?
        @posts = @posts.where(user_id: current_user.id)
      end
      if !params[:sort].nil?
        @posts = @posts.order(params[:sort] => params[:dir].to_sym)
      end
      date_dir = (params[:date_dir] || :desc).to_sym
      @posts = @posts.order(published: :asc, created_at: date_dir).page(params[:page])
      @is_admin = admin_user?
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Cannot view all posts.' }
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @tenants = tenants_sorted
    @tenant = Tenant.find(@post.tenant_id)
    @user = User.find(@post.user_id)
  end

  # GET /posts/new
  def new
    @post = Post.new\
      published: true
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge!\
      user_id: current_user.id,
      tenant_id: current_user.tenant_oid
    )

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :body, :published)
    end

    def correct_user
      if admin_user?
        @post = Post.find(params[:id])
      else
        @post = current_user.posts.find(params[:id])
      end
      if @post.nil?
        redirect_to posts_url
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def date_posted
    self.created_at.to_formatted_s(:my_format)
  end
end

app/views/posts/_form.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br
    = f.text_field :title, size: 80, maxlength: 255
  .field
    = f.label :body
    %br
    = f.text_area :body, cols: 80, rows: 10
  .field
    = f.label :published
    %br
    = f.check_box :published
  .actions
    = f.submit

app/views/posts/edit.haml
%h1 Editing post
= render 'form'
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.haml
%h1
  = link_to "Posts", posts_path(sort: nil)

= form_tag posts_path, method: 'get' do
  %p
    = text_field_tag :search, params[:search]
    = check_box_tag(:title_body)
    = label_tag(:title_body, "Search title and body")
    = submit_tag "Search", name: nil

- if @posts.nil?
  %p No posts.
- else
  %table
    %thead
      %tr
        - if @is_admin
          %th
            Author
            = link_to "asc", posts_path(sort: :user_id, dir: :asc)
            = link_to "desc", posts_path(sort: :user_id, dir: :desc)
        %th
          Title
          = link_to "asc", posts_path(sort: :title, dir: :asc)
          = link_to "desc", posts_path(sort: :title, dir: :desc)
        %th
          Date
          = link_to "asc", posts_path(date_dir: :asc)
          = link_to "desc", posts_path(date_dir: :desc)
        %th Published
        %th{colspan: 2}
    %tbody
      - @posts.each do |post|
        %tr
          - if @is_admin
            %td= post.user_id
          %td.post-title= link_to (truncate post.title), post
          %td.post-date= post.created_at.strftime("%Y-%m-%d")
          %td{class: post.published ? "pub-yes" : "pub-no"}
            = post.published ? "Y" : "N"
          %td= link_to 'Edit', edit_post_path(post)
          %td= link_to "Delete", post, method: :delete, |
            data: { confirm: 'Are you sure?' }
  = paginate @posts

app/views/posts/new.haml
%h1 New post

= render 'form'

app/views/posts/show.haml
- if !notice.nil?
  %p#notice= notice

%h1
  &bull;&nbsp;
  = @tenant.name

%h2.title= @post.title

%p
  %span.post-meta
    by
    %span.author= @user.name
    &bull;
    %span.date= @post.date_posted
%hr

%p= simple_format @post.body