config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'welcome#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'dashboard' => 'dashboard#index'

  get 'tenants' => 'tenants#index'
  get 'tenants/show'

  resources :users

end

app/views/layouts/_posts_listing.haml
.posts-listing
  - @posts.sort {|a, b| b.created_at <=> a.created_at }.each do |post|
    %h2.post-title= link_to post.title, post
    %p
      %span.post-meta
        - u = User.find(post.user_id)
        %span.post-tenant= Tenant.find(u.tenant_oid).name
        &bull;
        %span.post-date= User.find(post.user_id).name
        &bull;
        %span.post-date= post.date_posted
    %p.post-body
      - post_body_trunc, link = truncate_paragraph(post.body, post)
      = simple_format(truncate(post_body_trunc, |
          length: 200, |
          separator: ' ')) + link
  = paginate @posts

app/views/layouts/_sidebar.haml
%nav
  .level0= link_to raw("FIDO&nbsp;Company&nbsp;Blog"), root_path
  - if @tenants
    .level0.tenant-header Departments
    - @tenants.each do |t|
      .level0.tenant-name= link_to t.name, tenants_path(name: t.name)
  - if logged_in?
    .level0= link_to "Dashboard", dashboard_path
    .level0= link_to "Posts", posts_path
    .level0= link_to "New Post", new_post_path
    - if admin_user?
      .level0= link_to "Users", users_path
    .level0= link_to "Log out", logout_path, method: "delete"
  - else
    .level0= link_to "Log in", login_path

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title Fido
    = stylesheet_link_tag 'application', |
      media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #sidebar= render 'layouts/sidebar'
    #content-yield= yield